" General Settings

let hostname = substitute(system('hostname'),'\n','','')
let tmv = substitute(system('tmux -V'),'\n','','')

filetype on
filetype indent on

if hostname != "proteusi01" && hostname != "proteusa01" && hostname != "staph"
        set t_Co=256
        let g:solarized_termcolors=256
        colorscheme solarized
        set background=dark
endif

set undodir=~/.vim/.undo//
set backupdir=~/.vim/.backup//
set directory=~/.vim/.swp//

set dict=/usr/share/dict/words
set cursorline
set showcmd
set ruler
set incsearch
set wildmenu
syntax enable
set synmaxcol=0
set display=uhex
set shortmess=aAIsT
set cmdheight=2
set nowrap
if &diff
    set wrap
endif
set diffopt+=iwhite
let &scrolloff=999-&scrolloff
set smartcase
set relativenumber
set nowritebackup

set completeopt=menu
set mousemodel=popup
set backspace=2
set number
set nocompatible

set enc=utf-8
set fillchars=vert:¦

set expandtab
set tabstop=4
set shiftwidth=4
set foldcolumn=1
set cc=+1,+2

set linespace=0
set history=1000
set list listchars=tab:› ,trail:-,extends:>,precedes:<,eol:¬

set wrap

set hlsearch
set showmatch
set autoindent
set smartindent
set colorcolumn=100

let mapleader='\'

" General Key Bindings

no <down> ddp
no <left> <Nop>
no <right> <Nop>
no <up> ddkP

imap ;; <Esc>

nnoremap Q <Nop>

nmap ZZ :wq!<cr>
imap ZZ <Nop>
vmap ZZ <Nop>
nmap QQ :qa!<cr>
imap QQ <Nop>
vmap QQ <Nop>
nmap WW :w<cr>
imap WW <Nop>
vmap WW <Nop>
